name: Deploy Nginx

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Code checkout
      uses: actions/checkout@v2

    # Authenticate with Google Cloud using credentials_json (service account key)
    - name: Google Cloud Authentication
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Install the gcloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT }}  # Use secret for project ID
        install_components: 'gke-gcloud-auth-plugin'
        export_default_credentials: true

    - name: Build and push the Docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}  # Ensure this is the correct secret for your project ID
      run: |
        # Authenticate Docker with Google Cloud registry
        gcloud auth configure-docker us-central1-docker.pkg.dev

        # Ensure the GOOGLE_PROJECT variable is set correctly (print it to debug)
        echo "Google Project: $GOOGLE_PROJECT"
        
        # Build Docker image using the correct context (project-root folder) and Dockerfile location
        docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT/demo/nginx:latest -f project-root/Dockerfile .

        # Push Docker image to the registry
        docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT/demo/nginx:latest

    - name: Deploy to GKE
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        # Get credentials for the GKE cluster
        gcloud container clusters get-credentials mycluster1 --region us-central1-c

        # Replace project ID in the resources.yaml (if necessary)
        sed -i "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" resources.yaml
        
        # Apply the deployment configuration
        kubectl apply -f resources.yaml
