name: Deploy Nginx

on:
  push:
    branches:
    - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Code checkout
      uses: actions/checkout@v2

    # Authenticate with Google Cloud using credentials_json (service account key)
    - name: Google Cloud Authentication
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Install the gcloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT }}
        install_components: 'gke-gcloud-auth-plugin'
        export_default_credentials: true

    - name: Build and push the Docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev
        docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT/demo/nginx:latest .
        docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT/demo/nginx:latest

    - name: Deploy to kubernetes
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud container clusters get-credentials mycluster1 --zone us-central1-c
        sed -i "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" resources.yaml
        kubectl apply -f resources.yaml
